import fs from "fs";
import path from "path";
import solc from "solc";
import { ethers } from "ethers";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

const ARC_RPC = process.env.ARC_RPC_URL || "https://rpc.testnet.arc.network";
const USDC = process.env.USDC_ADDRESS || "0x3600000000000000000000000000000000000000";
const ADMIN = process.env.ADMIN_ADDRESS || "0xe8Bda2Ed9d2FC622D900C8a76dc455A3e79B041f";
const PRIVATE_KEY =
  process.env.DEPLOYER_PRIVATE_KEY ||
  "0xdf43d1545f8be3c8cc95f0737e64f7241cc05b9a90a470d61cc2a728809d4216";

function compile(fileName, contractName) {
  const source = fs.readFileSync(path.join(root, "contracts", fileName), "utf8");
  const input = {
    language: "Solidity",
    sources: { [fileName]: { content: source } },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      outputSelection: { "*": { "*": ["abi", "evm.bytecode"] } },
    },
  };
  const out = JSON.parse(solc.compile(JSON.stringify(input)));
  if (out.errors?.some((e) => e.severity === "error")) {
    console.error(out.errors);
    throw new Error("Compile failed: " + fileName);
  }
  const c = out.contracts[fileName][contractName];
  return { abi: c.abi, bytecode: c.evm.bytecode.object };
}

async function main() {
  const provider = new ethers.JsonRpcProvider(ARC_RPC, {
    chainId: 5042002,
    name: "arc-testnet",
  });
  const wallet = new ethers.Wallet(PRIVATE_KEY, provider);
  console.log("Deployer:", wallet.address);
  console.log("Admin owner:", ADMIN);

  const bal = await provider.getBalance(wallet.address);
  console.log("Native balance (wei-like):", bal.toString());

  if (bal === 0n) {
    console.error(
      "\nNO GAS. Fund deployer with Arc Testnet USDC from https://faucet.circle.com\nAddress:",
      wallet.address
    );
    const score = compile("GasRunScore.sol", "GasRunScore");
    const vault = compile("GasRunVault.sol", "GasRunVault");
    fs.writeFileSync(
      path.join(root, "contracts", "artifacts.json"),
      JSON.stringify(
        {
          chainId: 5042002,
          usdc: USDC,
          admin: ADMIN,
          deployer: wallet.address,
          privateKey: PRIVATE_KEY,
          score: { abi: score.abi, bytecode: "0x" + score.bytecode },
          vault: { abi: vault.abi, bytecode: "0x" + vault.bytecode },
          deployed: false,
        },
        null,
        2
      )
    );
    console.log("Wrote contracts/artifacts.json (not deployed yet)");
    process.exit(2);
  }

  const scoreArt = compile("GasRunScore.sol", "GasRunScore");
  const vaultArt = compile("GasRunVault.sol", "GasRunVault");

  const Score = new ethers.ContractFactory(scoreArt.abi, scoreArt.bytecode, wallet);
  const score = await Score.deploy();
  await score.waitForDeployment();
  const scoreAddr = await score.getAddress();
  console.log("GasRunScore:", scoreAddr);

  const Vault = new ethers.ContractFactory(vaultArt.abi, vaultArt.bytecode, wallet);
  const vault = await Vault.deploy(USDC, ADMIN, wallet.address);
  await vault.waitForDeployment();
  const vaultAddr = await vault.getAddress();
  console.log("GasRunVault:", vaultAddr);

  const result = {
    chainId: 5042002,
    rpc: ARC_RPC,
    usdc: USDC,
    admin: ADMIN,
    deployer: wallet.address,
    privateKey: PRIVATE_KEY,
    score: { address: scoreAddr, abi: scoreArt.abi },
    vault: { address: vaultAddr, abi: vaultArt.abi },
    deployed: true,
    deployedAt: new Date().toISOString(),
  };

  fs.writeFileSync(path.join(root, "contracts", "artifacts.json"), JSON.stringify(result, null, 2));
  fs.writeFileSync(
    path.join(root, "contracts", "deployed.json"),
    JSON.stringify(
      {
        score: scoreAddr,
        vault: vaultAddr,
        usdc: USDC,
        admin: ADMIN,
        operator: wallet.address,
        chainId: 5042002,
      },
      null,
      2
    )
  );

  fs.writeFileSync(
    path.join(root, "contracts-config.js"),
    `// Auto-generated by scripts/deploy.mjs
window.__GASRUN_CONTRACTS = {
  chainId: 5042002,
  usdc: "${USDC}",
  score: "${scoreAddr}",
  vault: "${vaultAddr}",
  admin: "${ADMIN}",
  operator: "${wallet.address}"
};
`
  );

  // patch .env addresses if file exists
  try {
    const envPath = path.join(root, ".env");
    if (fs.existsSync(envPath)) {
      let env = fs.readFileSync(envPath, "utf8");
      env = env.replace(/VAULT_ADDRESS=.*/g, `VAULT_ADDRESS=${vaultAddr}`);
      env = env.replace(/SCORE_ADDRESS=.*/g, `SCORE_ADDRESS=${scoreAddr}`);
      if (!env.includes("VAULT_ADDRESS=")) env += `\nVAULT_ADDRESS=${vaultAddr}\n`;
      if (!env.includes("SCORE_ADDRESS=")) env += `SCORE_ADDRESS=${scoreAddr}\n`;
      fs.writeFileSync(envPath, env);
    }
  } catch {}

  console.log("\nSaved artifacts, deployed.json, contracts-config.js, .env");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
